### ISSUE TITLE
thread panic with interact subcommand

### ISSUE THREAD

**Issue by nothingnesses** [myfreeweb/freepass#14]
To reproduce:
```
cd freepass/cli
cargo build --release
strip target/release/freepass 
mv target/release/freepass /usr/local/bin
RUST_BACKTRACE=1 freepass interact
```
Expected output: interactive repl displayed
Actual output:
```
thread 'main' panicked at 'Option file not found', src/main.rs:139:16                       
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: __libc_start_main
  11: <unknown>
```
Notes: help subcommand works though, so that's helpful.

**Comment by valpackett** [comment]
> file not found

Well, you didn't specify the `-f` flag or the `FREEPASS_FILE` environment variable, so it doesn't know which file to use.

I'll make error messages more user-friendly at some point in the future :)

**Comment by nothingnesses** [comment]
Ah right, silly me. It does work, thanks. For those who don't know, the command has to be in the format:
```
freepass -n "Your Name" -f "/location/of/vault" interact
```

**Comment by valpackett** [comment]
You don't have to type "interact", it's the default command
