### ISSUE TITLE
Running/Building freepass broken with latest libsodium release.

### ISSUE THREAD

**Issue by Reisen** [myfreeweb/freepass#15]
From the most recent `libsodium` CHANGELOG:

> - The aes128ctr primitive was removed. It was slow, non-standard, not authenticated, and didn't seem to be used by any opensource project.

Updating my system broke freepass so I've had to build an older copy of libsodium to deal with this for the time being.

**Comment by valpackett** [comment]
Thanks for reporting this! Now using rust-crypto for AES.
