### ISSUE TITLE
Consider dual licensing

### ISSUE THREAD

**Issue by aochagavia** [myfreeweb/freepass#2]
Not all legislations allow releasing code to the public domain, nor recognize the UNLICENSE as valid. To solve this, you should consider dual licensing your project. This would allow the user to choose which license to use. Maybe a possible alternative is the MIT license (see https://github.com/BurntSushi/fst, which is dual-licensed under MIT and the UNLICENSE).

See [this stack exchange question](http://programmers.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense) for details about the problems with UNLICENSE.

**Comment by valpackett** [comment]
¯\_(ツ)_/¯

If [SQLite doesn't care about that stuff](https://www.sqlite.org/copyright.html), my little project shouldn't either.

**Comment by aochagavia** [comment]
Thanks, I learned something new today :wink: !
