### ISSUE TITLE
Support for KeePass(X) keyring?

### ISSUE THREAD

**Issue by shackra** [myfreeweb/freepass#3]
Oh, this project is awesome!

I was wondering if support for KeePass(X) was listed in your road map!

**Comment by valpackett** [comment]
Thanks :-)

I'm definitely NOT planning to support any third party keyring formats.
You can create an import tool though, using the freepass core library.

**Comment by valpackett** [comment]
Looks like there's [a Rust library for the `.kdbx` format](https://github.com/sseemayer/keepass-rs) now! It even uses my [secure string library](https://github.com/myfreeweb/secstr) :-)

I might just add the import functionality…

**Comment by elzorrorebelde** [comment]
That would be awesome as the export function doesn't work on KeePass 

Enviado desde mi dispositivo Samsung

-------- Mensaje original --------
De: Greg notifications@github.com 
Fecha: 05/02/2016  11:00  (GMT-06:00) 
Para: myfreeweb/freepass freepass@noreply.github.com 
Cc: Jorge Araya Navarro shackra@riseup.net 
Asunto: Re: [freepass] Support for KeePass(X) keyring? (#3) 

Looks like there's a Rust library for the .kdbx format now! It even uses my secure string library :-)

I might just add the import functionality…

**Comment by valpackett** [comment]
Import works now:

``` bash
$ freepass -f yourvault.fpass mergein -i kdbx -F youroldvault.kdbx
```

**Comment by elzorrorebelde** [comment]
Awesome, God bless you and your good work! 

Enviado desde mi dispositivo Samsung

-------- Mensaje original --------
De: Greg notifications@github.com 
Fecha: 12/02/2016  6:29  (GMT-06:00) 
Para: myfreeweb/freepass freepass@noreply.github.com 
Cc: Jorge Araya Navarro shackra@riseup.net 
Asunto: Re: [freepass] Support for KeePass(X) keyring? (#3) 

Import works now:

$ freepass -f yourvault.fpass mergein -i kdbx -F youroldvault.kdbx

**Comment by elzorrorebelde** [comment]
Coming back to this, I'm getting this error if I enter the password for my `yourvault.fpass`:

```
thread '<main>' panicked at 'Couldn't read/decrypt freepass vault: CodecError(Decode(TypeMismatch { expected: Map, got: UInt32 }))', src/libcore/result.rs:760
```

and I get this error when entering the password for `youroldvault.kdbx`:

```
thread '<main>' panicked at 'Couldn't read/decrypt freepass vault: CodecError(AtOffset { kind: Other("invalid utf-8: invalid byte near index 0"), offset: 11 })', src/libcore/result.rs:760
```

This is the output of my `locale` command:

```
LANG=es_CR.utf8
LC_CTYPE=es_CR.utf8
LC_NUMERIC=es_CR.utf8
LC_TIME=es_CR.utf8
LC_COLLATE=es_CR.utf8
LC_MONETARY=es_CR.utf8
LC_MESSAGES=es_CR.utf8
LC_PAPER=es_CR.utf8
LC_NAME=es_CR.utf8
LC_ADDRESS=es_CR.utf8
LC_TELEPHONE=es_CR.utf8
LC_MEASUREMENT=es_CR.utf8
LC_IDENTIFICATION=es_CR.utf8
LC_ALL=
```

am I missing something?

**Comment by valpackett** [comment]
That's weird... Try a fresh freepass vault and a fresh keepass vault. Can you provide a minimal test case?

**Comment by elzorrorebelde** [comment]
Ok, now doing what you asked makes the prompt ask me for a password twice, for the fpass file and my KeePass test file I'm using the same password, error:

```
$ freepass -f newvault.fpass mergein -i kdbx -F NewDatabase.kdbx
thread '<main>' panicked at 'Could not read the file as kdbx: KeepassReadError(IncorrectKey)', src/libcore/result.rs:760
```

The file fpass is not created thought...

File: [NewDatabase.kdbx.zip](https://github.com/myfreeweb/freepass/files/241455/NewDatabase.kdbx.zip) The password is `secret123`
