### ISSUE TITLE
Consider 0.x.y version numbers

### ISSUE THREAD

**Issue by mokasin** [myfreeweb/freepass#9]
For making distro packages, it would be great if you could provide some kind of version incrementing. Having '0.0.0' for every published version doesn't reflect any differences in the builds. If you follow semver, the 0.x.y releases are fine for an unstable product.

**Comment by valpackett** [comment]
Of course I'll do that eventually, but for now, there are NO releases. I have not published any versions.

**Comment by mokasin** [comment]
I see. Because there is already a package in the user repositories of ArchLinux, I presumed, it is more or less production ready.

**Comment by valpackett** [comment]
AUR package?! I was not aware of that.
